### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by datenreisender**
No functional changes, just a bunch of smaller or bigger cleanups. 

It is probably easiest to look at the changes one-by-one especially because the first commit 37bd405 mainly consists of formatting changes because of the switch to prettier. These format changes otherwise make it hard to see the other changes. If you prefer to see just the changes without the introduction of prettier, you can also look at https://github.com/NordicSemiconductor/pc-nrfconnect-rssi/compare/37bd405...cleanup.

The last commit 956bbc4 converts the whole project to TypeScript which of course also included quite some changes, but for several files it also just meant changing the filename.

### CODE REVIEW

**Comment by deerob4** [comment]
I think your TypeScript changes are really good. The `RssiAction` union in particular is very nice for getting an overview of everything that can be done in the application; if you squint, it's almost like writing Elm or OCaml.

There's very little I'd change, but here are a couple of suggestions:

* The `RssiState` type is declared as a `type`, but an interface would be a better fit, as that's usually the goto when describing structures. Interfaces can be extended, which is occasionally useful. It's also more consistent with how you've typed the rest of the application.

* Although we're using Immer, our application state is still immutable. We never want to change it directly. This can be enforced by prepending the `readonly` keyword to each of the names in the `RssiState` interface, i.e. `readonly isPaused: boolean`. This prevents assignment to a state object, and also warns when mutable methods like `push` and `splice`. I also need to do this in the Direction Viewer.

* Though it's not so bad right now, there is quite a lot of boilerplate caused by typing the actions. We have to create the enum type, make an interface, the action creator itself, and then add the interface to the action type. In the future, we might want to consider using the [typesafe-actions](https://github.com/piotrwitek/typesafe-actions) library to cut down on this. There's quite a lot to the library, but it's easy to use just what you need. This is probably a better idea when the team as a whole is more comfortable with TypeScript, since it does add some complexity.

Overall, nice job 😁

**Comment by datenreisender** [comment]
Ah Elm! When creating the new architecture, I had the dream to make it so technology-independent to also allow writing apps with Elm. Did not quite manage that, obviously, but maybe someday … wouldn't it be nice to have a hackaton sometime again and then try this! ;-) 

I often do not know whether I should use a `type` or an `interface`. Will switch the `RssiState` to be an interface.

But speaking of `readonly`, which I had forgotten about, thanks for pointing it out: Instead of marking every property as `readonly` there is a way to mark them all together by using `type` which is not possible with `interface`: 
```typescript
type RssiState = Readonly<{
    isPaused: boolean;
    buffer: number[];
    // …
}>;
```
Do you consider that too hacky?

But somehow I must be doing something wrong regarding `readonly`. In 2857d5e5 I marked the fields as `readonly` and then mutate a property on the initial state. I had assumed, that this would yield an error but it does not. Do you have an idea what I am doing wrong?

**Comment by deerob4** [comment]
Regarding interfaces vs types, I tend to use interfaces for things like object and class definitions (akin to how the word is used in OOP), and types for "derivatives", things that build on already existing types. That to me seems like a useful distinction, but there are arguments either way.

I think the use of the `Readonly<T>` generic is perfectly fine. My personal preference is to use the `readonly` keyword, because I prefer to have the main type by itself, rather than as an argument to another type. That's a pretty spurious / overly aesthetic line of thinking though, so I think it's up to you what you prefer. I suppose one benefit is that there might in the future be some reason where we do need to mutate a value (for performance reasons or similar), in which case it's easier to remove one keyword on one line than have to redo the entire type.

I also assumed that what you do in 2857d5e would result in an error, so I think it was me who was wrong about the effects of the `readonly` keyword. It seems like it only prevents reassigning; for example,

```js
initialState.dataMax = []
```

would result in an error. That's not quite as useful, but it's still a good safeguard. I suppose it makes sense - to work as I had thought it did, the language would need a way of identifying which methods result in a mutation. Since there's no mechanism for that in JavaScript (that I know of), determining if mutation occurs is undecidable, à la the halting problem.

**Comment by datenreisender** [comment]
Regarding the boilerplate: I also noticed this unpleasantly when I changed the actions. But after all it was only there that it was so big. 

I also tried to do without the explicit types for actions by utilising `ReturnType`, but unfortunately TypeScript deduced too weak types. I have no experience with `typesafe-actions`, just used [redux-act](https://github.com/pauldijou/redux-act) but also liked that. Nowadays [Redux Toolkit](https://redux-toolkit.js.org/api/createAction) also seems getting more traction. So, yes, we should improve that in the future.

**Comment by datenreisender** [comment]
Regarding `readonly`: I dug a bit deeper and now understood my misconception. As you wrote, `readonly` on the property only prevents reassigning something new to the property. But TypeScript _does_ have a way to prevent mutating an array: Instead of using the type `number[]` one can use the type `readonly number[]`. So the line correctly reads as 
```ts
readonly dataMax: readonly number[];
```
A bit clunky, but that actually leads to errors when I try to mutate the array. (Instead of `readonly number[]` it has the same effect to use the type `ReadonlyArray<number>`, but I think the latter is not so nice, it is just the older variant to achieve the same). 

The same needs to be done for the tuples and it gets a bit more complex for the two dimensional array, but luckily we seldom have those. All put together this makes the type look like this:
```ts
interface RssiState {
    readonly isPaused: boolean;
    readonly buffer: readonly number[];
    readonly data: readonly (readonly number[])[];
    readonly dataMax: readonly number[];
    readonly delay: number;
    readonly scanRepeat: number;
    readonly maxScans: number;
    readonly animationDuration: number;
    readonly channelRange: readonly [number, number];
    readonly levelRange: readonly [number, number];
    readonly port: string | null;
}
```

I now also have an idea what I have confused it with: With [const assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) there the deeper elements are also immutable. So e.g. with 
```ts
const example = {
    length: 10,
    elements: [1, 2, 3],
} as const;
```
The array in `elements` also automatically gets the type `ReadonlyArray` and thus cannot be mutated. But const assertions really are for a different use case, so I will use the interface from above.

**Comment by datenreisender** [comment]
This is now ready for review again

**Review by deerob4 — APPROVED** [review]

**Pull request merged**
